[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.filesystem = spiffs

lib_deps =
  bblanchon/ArduinoJson@^6.21.6
  waspinator/AccelStepper@^1.64
  teemuatlut/TMCStepper@^0.7.3
  plerup/EspSoftwareSerial